#!/bin/bash
NDVMUUID=`xec-vm -n Network get uuid`
#DEBUG: echo $1 $2 >> /network
if [ "x$1" != "x$NDVMUUID" ]; then
    exit 0
fi

if [ "x$2" != "xrunning" ]; then
    exit 0
fi
#DEBUG: echo running daemon nw attach >> /network
nohup /etc/xen/scripts/nw-attach &
